{{- if and (.Values.serviceAccount) (.Values.serviceAccount.create) }}
{{- if not (lookup "v1" "ServiceAccount" "$.Release.Namespace" "mcp-admin") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcp-management-platform.serviceAccountName" . }}
  labels:
    {{- include "mcp-management-platform.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- end }}