apiVersion: v1
kind: Secret
metadata:
  name: mc-identity-registry-secrets
type: Opaque
data:
  mir_api_config: {{  .Values.global.mir_api_config | default "" | b64enc | quote }}
  mir_api_keycloak_json: {{ .Values.global.mir_api_keycloak_json | default "" | b64enc | quote }}
  mir_api_subca_keystore: {{ .Values.global.mir_api_subca_keystore | default "" | quote }}
  mir_api_truststore: {{ .Values.global.mir_api_truststore | default "" | quote }}

