apiVersion: v1
kind: Secret
metadata:
  name: mc-identity-registry-secrets
type: Opaque
data:
  mir_api_config: {{  .Values.global.mc_identity_registry.configuration | default "" | b64enc | quote }}
  mir_api_keycloak_json: {{ .Values.global.mc_identity_registry.keycloak_json | default "" | b64enc | quote }}
  mir_api_subca_keystore: {{ .Values.global.mc_identity_registry.keystore | default "" | quote }}
  mir_api_truststore: {{ .Values.global.mc_identity_registry.truststore | default "" | quote }}

