apiVersion: v1
kind: Secret
metadata:
  name: mc-identity-registry-secrets
type: Opaque
data:
  mir_api_config: {{ .Files.Get "config/application.yaml"  | b64enc | quote }}
  mir_api_keycloak_json: {{ .Files.Get "config/keycloak.json" | b64enc | quote }}
  mir_api_subca_keystore: {{ .Files.Get "config/subca-keystore.jks" | b64enc | quote }}
  mir_api_truststore: {{ .Files.Get "config/mcp-truststore.jks" | b64enc | quote }}

