{{- if not (lookup "v1" "Secret" "$.Release.Namespace" "mc-service-registry-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: mc-service-registry-secrets
type: Opaque
data:
  msr_database_username: {{ .Values.global.mc_service_registry.db_username | default "" | b64enc | quote }}
  msr_database_password: {{ .Values.global.mc_service_registry.db_password | default "" | b64enc | quote }}
  msr_keycloak_client_secret: {{ .Values.global.mc_service_registry.keycloak_client_secret | default "" | b64enc | quote }}
  own_edge_router_keystore: {{ .Values.global.mc_service_registry.own_edge_router_keystore | default "" | quote }}
  own_edge_router_keystore_password: {{ .Values.global.mc_service_registry.own_edge_router_keystore_password | default "" | b64enc | quote }}
  secom_signing_identity_keystore: {{ .Values.global.mc_service_registry.secom_signing_identity_keystore | default "" | quote }}
  secom_signing_identity_keystore_password: {{ .Values.global.mc_service_registry.secom_signing_identity_keystore_password | default "" | b64enc | quote }}
  secom_truststore: {{ .Values.global.mc_service_registry.secom_truststore | default "" | quote }}
  secom_truststore_password: {{ .Values.global.mc_service_registry.secom_truststore_password | default "" | b64enc | quote }}
{{- end }}