{{- if not (lookup "v1" "Secret" "$.Release.Namespace" "mc-service-registry-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: mc-service-registry-secrets
type: Opaque
data:
  msr_database_username: {{ .Values.global.mc_service_registry.db_username | default "" | b64enc | quote }}
  msr_database_password: {{ .Values.global.mc_service_registry.db_password | default "" | b64enc | quote }}
  msr_keycloak_client_secret: {{ .Values.global.mc_service_registry.keycloak_client_secret | default "" | b64enc | quote }}
  msr_ledger_address: {{ .Values.global.mc_service_registry.ledger_address | default "" | b64enc | quote }}
  msr_ledger_credentials: {{ .Values.global.mc_service_registry.ledger_credentials | default "" | b64enc | quote }}
{{- end }}