{{- if not (lookup "v1" "Secret" "$.Release.Namespace" "mc-mms-edge-router-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: mc-mms-edge-router-secrets
type: Opaque
data:
  client_certificate: {{ .Values.global.mc_mms_edge_router.client_certificate | default "" | b64enc | quote }}
  client_certificate_key: {{ .Values.global.mc_mms_edge_router.client_certificate_key | default "" | b64enc | quote }}
  certificate: {{ .Values.global.mc_mms_edge_router.certificate | default "" | b64enc | quote }}
  certificate_key: {{ .Values.global.mc_mms_edge_router.certificate_key | default "" | b64enc | quote }}
  client_ca: {{ .Values.global.mc_mms_edge_router.client_ca | default "" | b64enc | quote }}
{{- end }}