{{- if not (lookup "v1" "Secret" "$.Release.Namespace" "mcp-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: mc-keycloak-secrets
type: Opaque
data:
  keycloak_db_username: {{ .Values.global.keycloak_db_username | default "" | b64enc | quote }}
  keycloak_db_password: {{ .Values.global.keycloak_db_password | default "" | b64enc  | quote}}
  keycloak_admin: {{ .Values.global.keycloak_admin | default "" | b64enc | quote }}
  keycloak_admin_password: {{ .Values.global.keycloak_admin_password | default "" | b64enc | quote }}
  keycloak_idbroker_updater: {{ .Values.global.keycloak_idbroker_updater | default "" | quote }}
  keycloak_keystore_password: {{ .Values.global.keycloak_keystore_password | default "" | b64enc | quote }}
  keycloak_truststore: {{ .Values.global.keycloak_truststore | default "" | quote }}
  keycloak_truststore_password: {{ .Values.global.keycloak_truststore_password | default "" | b64enc | quote }}
{{- end }}