{{- if not (lookup "v1" "Secret" "$.Release.Namespace" "mc-keycloak-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: mc-keycloak-secrets
type: Opaque
data:
  keycloak_db_username: {{ .Values.global.mc_keycloak.db_username | default "" | b64enc | quote }}
  keycloak_db_password: {{ .Values.global.mc_keycloak.db_password | default "" | b64enc  | quote}}
  keycloak_admin: {{ .Values.global.mc_keycloak.admin_username | default "" | b64enc | quote }}
  keycloak_admin_password: {{ .Values.global.mc_keycloak.admin_password | default "" | b64enc | quote }}
  keycloak_idbroker_updater: {{ .Values.global.mc_keycloak.keystore | default "" | quote }}
  keycloak_keystore_password: {{ .Values.global.mc_keycloak.keystore_password | default "" | b64enc | quote }}
  keycloak_truststore: {{ .Values.global.mc_keycloak.truststore | default "" | quote }}
  keycloak_truststore_password: {{ .Values.global.mc_keycloak.truststore_password | default "" | b64enc | quote }}
{{- end }}