# Default values for mc-keycloak.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:

  #
  # Common Variables
  #
  keycloak_url: "http://localhost/mcp"
  keycloak_realm: "MCP"

  # The MCP Keycloak Chart
  mc_keycloak:
    #
    # Input Files
    # 
    keystore: ""
    truststore: ""
    #
    # Credentials
    #
    db_username: "admin"
    db_password: "changeit"
    admin_username: "admin"
    admin_password: "changeit"
    keystore_password: "changeit"
    truststore_password: changeit"
    #
    # Other Configuration
    #
    db_type: "postgres"
    db_url: "jdbc:postgresql://localhost/keycloak_mcp"
    auth_url: "http://localhost/mcp/auth"
    admin_url: "http://localhost/mcp/auth"
    mir_url: "http://localhost/mcp/mir"

replicaCount: 1

image:
  repository: ghcr.io/maritimeconnectivity/mcpkeycloakspi
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "mcp-admin"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8090
  externalIPs:
    - 10.0.1.42 

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: mc-keycloak.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

env:
  - name: KC_HOSTNAME_URL
    valueFrom:
      configMapKeyRef:
        name: mc-keycloak-config
        key: keycloak_auth_url
  - name: KC_HOSTNAME_ADMIN_URL
    valueFrom:
      configMapKeyRef:
        name: mc-keycloak-config
        key: keycloak_admin_url
  - name: KC_DB
    valueFrom:
      configMapKeyRef:
        name: mc-keycloak-config
        key: keycloak_db_type
  - name: KC_DB_URL
    valueFrom:
      configMapKeyRef:
        name: mc-keycloak-config
        key: keycloak_db_url
  - name: KC_DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: mc-keycloak-secrets
        key: keycloak_db_username
  - name: KC_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mc-keycloak-secrets
        key: keycloak_db_password
  - name: KEYCLOAK_ADMIN
    valueFrom:
      secretKeyRef:
        name: mc-keycloak-secrets
        key: keycloak_admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mc-keycloak-secrets
        key: keycloak_admin_password
  - name: KC_SPI_EVENTS_LISTENER_MCP_EVENT_LISTENER_SERVER_ROOT
    valueFrom:
      configMapKeyRef:
        name: mc-keycloak-config
        key: mcp_identity_registry_url
  - name: KC_SPI_EVENTS_LISTENER_MCP_EVENT_LISTENER_KEYSTORE_PATH
    value: "/mc-eventprovider-conf/idbroker-updater.jks"
  - name: KC_SPI_EVENTS_LISTENER_MCP_EVENT_LISTENER_KEYSTORE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mc-keycloak-secrets
        key: keycloak_keystore_password
  - name: KC_SPI_EVENTS_LISTENER_MCP_EVENT_LISTENER_TRUSTSTORE_PATH
    value: "/mc-eventprovider-conf/truststore.jks"
  - name: KC_SPI_EVENTS_LISTENER_MCP_EVENT_LISTENER_TRUSTSTORE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mc-keycloak-secrets
        key: keycloak_truststore_password

# livenessProbe:
#  httpGet:
#    path: /health/live
#    port: http
# readinessProbe:
#  httpGet:
#    path: /health/ready
#    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
- name: config-volume
  projected:
    sources:
    - secret:
        name: mc-keycloak-secrets
        items:
        - key: keycloak_truststore
          path: truststore.jks
    - secret:
        name: mc-keycloak-secrets
        items:
        - key: keycloak_idbroker_updater
          path: idbroker-updater.jks

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
- name: config-volume
  mountPath: "/mc-eventprovider-conf"
  readOnly: true

nodeSelector: {
  "kubernetes.io/os": linux
}

tolerations: []

affinity: {}
