apiVersion: v1
kind: Service
metadata:
  name: {{ include "mc-msr-ledger.fullname" . }}
  labels:
    {{- include "mc-msr-ledger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port_rpc }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.port_websocket }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "mc-msr-ledger.selectorLabels" . | nindent 4 }}
