# Default values for mcp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:

  #
  # Common Variables
  #
  keycloak_url: "http://localhost/mcp"
  keycloak_realm: "MCP"

  #
  # Per Child-Chart
  #

  # The MCP Keycloak Chart
  mc_keycloak:
    #
    # Input Files
    # 
    keystore: ""
    truststore: ""
    #
    # Credentials
    #
    db_username: "admin"
    db_password: "changeit"
    admin_username: "admin"
    admin_password: "changeit"
    keystore_password: "changeit"
    truststore_password: "changeit"
    #
    # Other Configuration
    #
    db_type: "postgres"
    db_url: "jdbc:postgresql://localhost/keycloak_mcp"
    auth_url: "http://localhost/mcp/auth"
    admin_url: "http://localhost/mcp/auth"
    mir_url: "http://localhost/mcp/mir"

  # The Identity Registry Chart
  mc_identity_registry:
    #
    # Input Files
    #
    configuration: ""
    keycloak_json: ""
    keystore: ""
    truststore: ""
    #
    # Credentials
    #
    
    #
    # Other Configuration
    #
  
  # The Service Registry Chart
  mc_service_registry:
    #
    # Input Files
    #

    #
    # Credentials
    #
    db_username: "admin"
    db_password: "changeit"
    keycloak_client_secret: "changeit"
    ledger_address: "0x000000000000000000000000000000000000000"
    ledger_credentials: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    #
    # Other Configuration
    #
    db_type: "postgresql"
    db_host: "localhost"
    db_port: 5432
    keycloak_client_id: "mcpsvreg"
    mir_api_url: "http://localhost/mcp/mir/oidc/api"
    ledger_host: "mc-msr-ledger.mcp"
    ledger_port: 8546
  
  # The MSR Ledger Chart
  mc_msr_ledger:
    #
    # Input Files
    #

    #
    # Credentials
    #
    
    #
    # Other Configuration
    #
  
  # The MMS Router Chart
  mc_mms_router:
    #
    # Input Files
    #
    private_key: ""
    certificate: ""
    certificate_key: ""
    client_ca: ""
    beacons: ""

    #
    # Credentials
    #
    
    #
    # Other Configuration
    #
    port: 8080
    port_libp2p: 9000

  # The MMS Edge Router Chart
  mc_mms_edge_router:
    #
    # Input Files
    #
    client_certificate: ""
    client_certificate_key: ""
    certificate: ""
    certificate_key: ""
    client_ca: ""

    #
    # Credentials
    #
    
    #
    # Other Configuration
    #
    port: 8080
    #mrn: "urn:mrn:mcp:device:idp1:org1:er"
    router_address: "localhost:8080"

  # The MCP Management Portal Chart
  mcp_management_portal:
    #
    # Input Files
    #

    #
    # Credentials
    #
    
    #
    # Other Configuration
    #
    name: "MCP Testbed"
    title: "MCP Testbed - Test Environment"
    identity_provider_mrn_namespace: "mcp"
    identity_registry_url: "https://localhost/mcp/mir"
    identity_registry_provider: "Maritime Connectivity Platform"
    identity_registry_email: "test@email.org"
    service_registry_url: "https://mcp.grad-rrnav.pub/mcp/msr"
    service_registry_provider: "Maritime Connectivity Platform"
    service_registry_email: "test@email.org"
    management_portal_provider: "Maritime Connectivity Platform"
    management_portal_email: "test@email.org"


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""


# The ingress is defined in the top level
ingress:
  enabled: true
  name: mcp-ingress
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: localhost
      paths:
        - path: /mcp/(auth)(.*)
          pathType: ImplementationSpecific
          serviceName: mc-keycloak
          servicePort: 8090
        - path: /(mcp/mir)(.*)
          pathType: ImplementationSpecific
          serviceName: mc-identity-registry
          servicePort: 8443
        - path: /(mcp/msr)(.*)
          pathType: ImplementationSpecific
          serviceName: mc-service-registry
          servicePort: 8444
        - path: /(mcp/mms)(.*)
          pathType: ImplementationSpecific
          serviceName: mc-mms-router
          servicePort: 8080
        - path: /(mcp/mms-p2p)(.*)
          pathType: ImplementationSpecific
          serviceName: mc-mms-router
          servicePort: 9000
        - path: /(mcp/mms-edge)(.*)
          pathType: ImplementationSpecific
          serviceName: mc-mms-edgerouter
          servicePort: 8080
        - path: /(mcp/mms-edge-p2p)(.*)
          pathType: ImplementationSpecific
          serviceName: mc-mms-edgerouter
          servicePort: 9000
        - path: /mcp/ledger()(.*)
          pathType: ImplementationSpecific
          serviceName: mc-msr-ledger
          servicePort: 8545
        - path: /mcp/portal()(.*)
          pathType: ImplementationSpecific
          serviceName: mcp-management-portal
          servicePort: 4200
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
