{{- if not (lookup "v1" "Secret" "$.Release.Namespace" "mc-mms-router-secrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: mc-mms-router-secrets
type: Opaque
data:
  private_key: {{ .Values.global.mc_mms_router.private_key | default "" | b64enc | quote }}
  certificate: {{ .Values.global.mc_mms_router.certificate | default "" | b64enc | quote }}
  certificate_key: {{ .Values.global.mc_mms_router.certificate_key | default "" | b64enc | quote }}
  client_ca: {{ .Values.global.mc_mms_router.client_ca | default "" | b64enc | quote }}
  beacons: {{ .Values.global.mc_mms_router.beacons | default "" | b64enc | quote }}
{{- end }}